version: '3'

services:
  # MySQL
  db:
    container_name: graphql-todo-mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./mysql/schema.sql:/var/ddl/schema.sql
      - ./script:/var/script
    ports:
      - 3306:3306

  redis:
    container_name: graphql-todo-redis
    image: redis:6.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - "./docker/redis:/data"
