// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package rdb

import (
	"time"
)

type Task struct {
	ID         string
	Title      string
	Text       string
	UserID     string
	PriorityID string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type TaskHasPriority struct {
	ID         int32
	TaskID     string
	PriorityID string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type TaskPriority struct {
	ID        string
	Value     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
