// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

var MockTodo = &Todo{
	ID:   "Title",
	Text: "Text",
	Done: true,
	User: &User{
		ID:   "1",
		Name: "Name",
	},
}

var MockUser = &User{
	ID:   "2",
	Name: "Name",
}
